# Generated by Django 5.1.4 on 2025-01-03 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('customer', 'مشتری'), ('supplier', 'تامین کننده')], default='customer', max_length=10, verbose_name='نقش'),
        ),
    ]
