# Generated by Django 5.1.6 on 2025-02-06 20:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='description',
        ),
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
        migrations.RemoveField(
            model_name='product',
            name='price',
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(blank=True, default='دسته\u200cبندی نشده', max_length=255, null=True, verbose_name='دسته\u200cبندی'),
        ),
        migrations.AddField(
            model_name='product',
            name='images',
            field=models.ImageField(blank=True, null=True, upload_to='product_images/'),
        ),
        migrations.AddField(
            model_name='product',
            name='initial_stock',
            field=models.PositiveIntegerField(default=0, verbose_name='موجودی اولیه'),
        ),
        migrations.AddField(
            model_name='product',
            name='long_description',
            field=models.TextField(default='توضیحات کامل ندارد', verbose_name='توضیحات کامل'),
        ),
        migrations.AddField(
            model_name='product',
            name='short_description',
            field=models.CharField(default='توضیحات کوتاه ندارد', max_length=500, verbose_name='توضیحات کوتاه'),
        ),
        migrations.AddField(
            model_name='product',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='product',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='قیمت واحد'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(default='محصول بدون نام', max_length=255, verbose_name='نام محصول'),
        ),
    ]
