# Generated by Django 4.2.17 on 2025-03-07 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0002_package_initial_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='قیمت واحد'),
        ),
    ]
