# Generated by Django 4.2.17 on 2025-03-07 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='initial_stock',
            field=models.PositiveIntegerField(default=0, verbose_name='موجودی اولیه'),
        ),
    ]
